[package]
name = "fourmeme"
version = "0.1.0"
edition = "2021"

[lib]
name = "fourmeme"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.100"
alloy = { version = "1.0.41", features = ["full"] }
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"


